[package]
name = "dns-proxy"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
chrono = "0.4.38"
curl = { version = "0.4.46", optional = true }
ctrlc = "3.4.5"

[features]
default = ["filter_update"]
filter_update = ["dep:curl"]
