FROM alpine

WORKDIR /usr/dns-adblock/
COPY ./target/armv7-unknown-linux-musleabihf/release/dns-proxy /usr/dns-adblock/dns-proxy
COPY ./local-blocklist.txt /usr/dns-adblock/local-blocklist.txt
COPY ./html/404.html /usr/dns-adblock/html/404.html
COPY ./html/change_ip.html /usr/dns-adblock/html/change_ip.html
COPY ./html/classes.css /usr/dns-adblock/html/classes.css
COPY ./html/start_page.html /usr/dns-adblock/html/start_page.html
COPY ./html/statistics.html /usr/dns-adblock/html/statistics.html

CMD ["/usr/dns-adblock/dns-proxy"]

