FROM ubuntu:24.04

RUN  apt-get update && apt-get -y install curl
WORKDIR /usr/dns-adblock/
# Executable
COPY ./target/release/dns-proxy /usr/dns-adblock/dns-proxy
# Local block list
COPY ./local-blocklist.txt /usr/dns-adblock/local-blocklist.txt
COPY ./local-whitelist.txt /usr/dns-adblock/local-whitelist.txt
# Config file
COPY ./config.json /usr/dns-adblock/config.json
# html files
COPY ./html/404.html /usr/dns-adblock/html/404.html
COPY ./html/change_ip.html /usr/dns-adblock/html/change_ip.html
COPY ./html/classes.css /usr/dns-adblock/html/classes.css
COPY ./html/start_page.html /usr/dns-adblock/html/start_page.html
COPY ./html/statistics.html /usr/dns-adblock/html/statistics.html
COPY ./html/tpool_stats.html /usr/dns-adblock/html/tpool_stats.html
COPY ./html/about.html /usr/dns-adblock/html/about.html
# Image  files
COPY ./html/images/banner.png /usr/dns-adblock/html/images/banner.png
COPY ./html/favicon.ico /usr/dns-adblock/html/favicon.ico

CMD ["/usr/dns-adblock/dns-proxy"]

